blastx -query nucleotide/seq/10000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >  prot_db/S.blastx.log 
blastx -query nucleotide/seq/1000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/101000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/102000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/103000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/104000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/105000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/106000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/107000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/108000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/109000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/110000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/11000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/111000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/112000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/113000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/114000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/115000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/116000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/117000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/118000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/119000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/120000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/12000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/121000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/122000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/123000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/124000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/125000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/126000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/127000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/128000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/129000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/130000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/13000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/131000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/132000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/133000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/134000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/135000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/136000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/137000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/138000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/139000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/140000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/14000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/15000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/16000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/17000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/18000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/19000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/20000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/2000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/21000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/22000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/23000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/24000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/25000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/26000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/27000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/28000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/29000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/30000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/3000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/31000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/32000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/33000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/34000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/35000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/36000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/37000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/38000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/39000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/40000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/4000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/41000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/42000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/43000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/44000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/45000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/46000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/47000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/48000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/49000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/50000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/5000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/51000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/52000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/53000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/54000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/55000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/56000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/57000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/58000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/59000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/60000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/6000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/61000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/62000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/63000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/64000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/65000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/66000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/67000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/68000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/69000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/70000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/7000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/71000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/72000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/73000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/74000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/75000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/76000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/77000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/78000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/79000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/80000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/8000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/81000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/82000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/83000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/84000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/85000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/86000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/87000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/88000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/89000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/90000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/9000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/91000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/92000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/93000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/94000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/95000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/96000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/97000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/98000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 
blastx -query nucleotide/seq/99000.fasta -evalue 1e-5 -subject protein/s_prot.fasta  >>   prot_db/S.blastx.log 

